import os
from pathlib import Path
import numpy as np
import pandas as pd
from scipy.stats import pearsonr

# ---------------------------------------------------------------------------
# 0. Configuration
# ---------------------------------------------------------------------------
DATA_DIR = Path(__file__).resolve().parent.parent / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

PREDICTORS_CSV = DATA_DIR / "phenology_flux_predictors_by_site_year_index.csv"  # script 6 output
CLUSTERS_CSV = DATA_DIR / "site_year_climate_clusters.csv"                      # script 10 output

OUTPUT_GRID_CSV = DATA_DIR / "climate_cluster_correlations.csv"            # every cluster x pair tested
OUTPUT_BEST_CSV = DATA_DIR / "climate_cluster_best_correlations.csv"       # best +/- cluster per pair

VI_INDICES = ['NDVI', 'NIRv']
AUTUMN_PARAMS = ['EOS90', 'EOS50', 'EOS10', 'senescence_kinetic_i']
SPRING_PARAMS = ['leaf_out_10', 'leaf_out_50', 'leaf_out_90', 'greenup_kinetic_i']
FLUX_PREDICTORS = ['total_gpp_growing_season', 'gpp_sos10_to_solstice', 'gpp_solstice_to_eos10',
                    'total_reco_growing_season', 'mean_radiation_growing_season',
                    'mean_temperature_growing_season', 'photoperiod_at_EOS90']
PREDICTORS = SPRING_PARAMS + ['growing_season_length'] + FLUX_PREDICTORS

# Smaller than script 6's pooled-correlation threshold, since splitting by
# climate cluster leaves far fewer site-years per group - but still a floor
# to avoid a 5-point "correlation" being reported as if it meant something.
MIN_PAIRS_FOR_CORR = 5

# Quality gate on the Landsat phenology curve fit - see script 6. Applied
# again here defensively, in case PREDICTORS_CSV was generated by an older
# run of script 6 that didn't yet filter on this.
MIN_FIT_CORR = 0.8

if not os.path.exists(PREDICTORS_CSV):
    raise FileNotFoundError(f"Missing '{PREDICTORS_CSV}'. Run the autumn-phenology-correlation script first.")
if not os.path.exists(CLUSTERS_CSV):
    raise FileNotFoundError(f"Missing '{CLUSTERS_CSV}'. Run the climate-clustering script first.")


# ---------------------------------------------------------------------------
# 1. Load + merge - each (site_id, year, vi_index) row gets its climate
#    cluster attached. A site-year not covered by the clustering script
#    (e.g. dropped there for insufficient climate-variable coverage) simply
#    won't have a cluster and is excluded via the inner join.
# ---------------------------------------------------------------------------
predictors_df = pd.read_csv(PREDICTORS_CSV)
predictors_df['year'] = predictors_df['year'].astype(int)
if 'corr' in predictors_df.columns:
    n_before = len(predictors_df)
    predictors_df = predictors_df[predictors_df['corr'] >= MIN_FIT_CORR].copy()
    if len(predictors_df) < n_before:
        print(f"Dropped {n_before - len(predictors_df)} row(s) with phenology fit corr < {MIN_FIT_CORR}.")

clusters_df = pd.read_csv(CLUSTERS_CSV)[['site_id', 'year', 'climate_cluster']]
clusters_df['year'] = clusters_df['year'].astype(int)

merged = predictors_df.merge(clusters_df, on=['site_id', 'year'], how='inner')
n_dropped = len(predictors_df) - len(merged)
print(f"{len(merged)} of {len(predictors_df)} phenology rows have a climate-cluster assignment "
      f"({n_dropped} dropped - no cluster available for that site-year).")

n_clusters = merged['climate_cluster'].nunique()
print(f"Climate clusters present: {sorted(merged['climate_cluster'].unique())}")

# ---------------------------------------------------------------------------
# 2. Correlate each autumn parameter against each predictor, SEPARATELY
#    within each climate cluster and VI index.
# ---------------------------------------------------------------------------
results = []
for vi in VI_INDICES:
    vi_sub = merged[merged['vi_index'] == vi]
    for cluster_id in sorted(vi_sub['climate_cluster'].unique()):
        cluster_sub = vi_sub[vi_sub['climate_cluster'] == cluster_id]
        for autumn_p in AUTUMN_PARAMS:
            if autumn_p not in cluster_sub.columns:
                continue
            for pred in PREDICTORS:
                if pred not in cluster_sub.columns:
                    continue
                pair = cluster_sub[[pred, autumn_p]].dropna()
                if len(pair) < MIN_PAIRS_FOR_CORR or pair[pred].std() == 0 or pair[autumn_p].std() == 0:
                    continue
                r, p_value = pearsonr(pair[pred], pair[autumn_p])
                results.append({
                    'vi_index': vi, 'climate_cluster': cluster_id,
                    'autumn_parameter': autumn_p, 'predictor': pred,
                    'n': len(pair), 'pearson_r': r, 'p_value': p_value,
                })

scan_df = pd.DataFrame(results)
scan_df.to_csv(OUTPUT_GRID_CSV, index=False)
print(f"\nPer-cluster correlations ({len(scan_df):,} rows) written to '{OUTPUT_GRID_CSV}'.")

# ---------------------------------------------------------------------------
# 3. Best positive and best negative cluster per (vi_index, autumn_param,
#    predictor) - i.e. which of the 8 climate groups shows the strongest
#    relationship in each direction.
# ---------------------------------------------------------------------------
best_rows = []
for (vi, autumn_p, pred), group in scan_df.groupby(['vi_index', 'autumn_parameter', 'predictor']):
    best_pos = group.loc[group['pearson_r'].idxmax()]
    best_neg = group.loc[group['pearson_r'].idxmin()]
    for label, row in [('most_positive', best_pos), ('most_negative', best_neg)]:
        best_rows.append({
            'vi_index': vi, 'autumn_parameter': autumn_p, 'predictor': pred,
            'correlation_type': label, 'climate_cluster': int(row['climate_cluster']),
            'n': int(row['n']), 'pearson_r': row['pearson_r'], 'p_value': row['p_value'],
        })

best_df = pd.DataFrame(best_rows)
best_df.to_csv(OUTPUT_BEST_CSV, index=False)
print(f"Best +/- cluster per (vi_index, autumn_parameter, predictor) written to '{OUTPUT_BEST_CSV}'.")

if not best_df.empty:
    top = best_df.reindex(best_df['pearson_r'].abs().sort_values(ascending=False).index).head(10)
    print("\nStrongest cluster-specific correlations overall (by |r|):")
    print(top[['vi_index', 'climate_cluster', 'autumn_parameter', 'predictor',
               'correlation_type', 'n', 'pearson_r', 'p_value']].to_string(index=False))